#!/bin/sh
# vim:ts=2:sw=2:et

set -e

dpkg-maintscript-helper rm_conffile /etc/kernel/postinst.d/linux-firmware-raspi3 1.20161123-2 -- "$@"
dpkg-maintscript-helper rm_conffile /etc/kernel/postrm.d/50raspi3-firmware -- "$@"
dpkg-maintscript-helper rm_conffile /etc/kernel/postinst.d/50raspi3-firmware -- "$@"
dpkg-maintscript-helper rm_conffile /etc/initramfs/post-update.d/50raspi3-firmware -- "$@"

#DEBHELPER#

exit 0
